import dbConnect from "../lib/db";
import Faculty from "../lib/models/Faculty";

const facultyData = [
    {
        name: "Mayuri Bhosale",
        designation: "Assistant Professor",
        qualification: "MSc Maths, SET",
        experience: "8",
        achievements: "No",
        subjects: "Maths & Statistics",
        email: "mayuribhosale@bkbck.edu.in",
    },
    {
        name: "Saba Shaikh",
        designation: "Assistant Professor",
        qualification: "MSc Comp Sci",
        experience: "7",
        achievements: "1",
        subjects: "Programming",
        email: "saba.shaikh@bkbck.edu.in",
    },
    {
        name: "Akash Kamble",
        designation: "Assistant Professor",
        qualification: "MSc IT",
        experience: "11",
        achievements: "Not Provided",
        subjects: "Cyber Security",
        email: "akash.kamble@bkbck.edu.in",
    },
    {
        name: "Kalpesh Gaikwad",
        designation: "Assistant Professor",
        qualification: "MSc Maths, B.Ed (Mathematics & Science)",
        experience: "11",
        achievements: "Not Provided",
        subjects: "Mathematics & Statistics",
        email: "kalpesh.gaikwad@bkbck.edu.in",
    },
    {
        name: "Prachi Adhiraj",
        designation: "Assistant Professor",
        qualification: "MSc CS",
        experience: "4",
        achievements: "Not Provided",
        subjects: "IT/Cs Programming",
        email: "prachi.adhiraj@bkbck.edu.in",
    },
    {
        name: "Hemangi Talele",
        designation: "Assistant Professor",
        qualification: "MSc CS, Mathematics, NET, PhD (Pursuing)",
        experience: "11",
        achievements: "Not Provided",
        subjects: "Programming",
        email: "hemangi.rane@bkbck.edu.in",
    },
    {
        name: "Ashwini Kulkarni",
        designation: "Assistant Professor",
        qualification: "BE, MCA",
        experience: "14",
        achievements: "Not Provided",
        subjects: "IT/Cs Programming",
        email: "ashwini.kulkarni@bkbck.edu.in",
    },
    {
        name: "Preeti Pareek",
        designation: "Assistant Professor",
        qualification: "MSc CS",
        experience: "1",
        achievements: "Not Provided",
        subjects: "IT/Cs Programming",
        email: "preeti.pareek@bkbck.edu.in",
    },
    {
        name: "Rohini Patil",
        designation: "Assistant Professor",
        qualification: "Not Provided",
        experience: "9",
        achievements: "Not Provided",
        subjects: "IT/Cs Programming",
        email: "rohini.patil@bkbck.edu.in",
    },
    {
        name: "Vrinda Patil",
        designation: "Assistant Professor",
        qualification: "MSc IT",
        experience: "5",
        achievements: "Not Provided",
        subjects: "IT/Cs Programming",
        email: "vrunda.patil@bkbck.edu.in",
    },
    {
        name: "Shreya Tiwari",
        designation: "Assistant Professor",
        qualification: "MSc IT",
        experience: "3",
        achievements: "Not Provided",
        subjects: "IT/Cs Programming",
        email: "shreya.tiwari@bkbck.edu.in",
    },
    {
        name: "Gauri Shirsat",
        designation: "Assistant Professor",
        qualification: "MCA",
        experience: "10",
        achievements: "Not Provided",
        subjects: "IT/Cs Programming",
        email: "gauri.shirsat@bkbck.edu.in",
    },
    {
        name: "Neha Chhatwani",
        designation: "Assistant Professor",
        qualification: "BSc IT, MCA, B.Ed",
        experience: "5",
        achievements: "Not Provided",
        subjects: "IT/Cs Programming",
        email: "neha.chhatwani@bkbck.edu.in",
    },
    {
        name: "Kiara Sangtani",
        designation: "Assistant Professor",
        qualification: "BCA, MCA",
        experience: "7",
        achievements: "Not Provided",
        subjects: "IT/Cs Programming",
        email: "kiara.sangtani@bkbirlacollegekalyan.com",
    },
    {
        name: "Vandana Maurya",
        designation: "Assistant Professor",
        qualification: "BE, ME, NET",
        experience: "12",
        achievements: "Not Provided",
        subjects: "IT/Cs Programming",
        email: "vandana.maurya@bkbck.edu.in",
    },
    {
        name: "Aakarshita Pandey",
        designation: "Assistant Professor",
        qualification: "MSc Comp Sci",
        experience: "1+",
        achievements: "Not Provided",
        subjects: "IT/Cs Csf Programming",
        email: "aakarshita.pandey@bkbck.edu.in",
    },
    {
        name: "Omkar Patil",
        designation: "Assistant Professor",
        qualification: "MSc Data Science",
        experience: "1",
        achievements: "Not Provided",
        subjects: "IT/Cs Csf Programming",
        email: "omkar.patil@bkbck.edu.in",
    },
    {
        name: "Zunaria Ansari",
        designation: "Assistant Professor",
        qualification: "MSc CS",
        experience: "1",
        achievements: "Not Provided",
        subjects: "IT/Cs Csf Programming",
        email: "zunaria.ansari@bkbck.edu.in",
    },
    {
        name: "Anjali Bunker",
        designation: "Assistant Professor",
        qualification: "UGC NET, MSc IT",
        experience: "3+",
        achievements: "Not Provided",
        subjects: "IT",
        email: "anjali.bunker@bkbck.edu.in",
    },
    {
        name: "Deepmala Maity",
        designation: "Assistant Professor",
        qualification: "MSc IT",
        experience: "3",
        achievements: "Not Provided",
        subjects: "IT/Cs Programming",
        email: "deepmala.maity@bkbck.edu.in",
    },
    {
        name: "Manasi Mali",
        designation: "Assistant Professor",
        qualification: "MSc AI",
        experience: "1",
        achievements: "Not Provided",
        subjects: "IT/Cs Programming",
        email: "manasi.mali@bkbck.edu.in",
    },
    {
        name: "Rajeshwari Mistri",
        designation: "Assistant Professor",
        qualification: "MSc AI",
        experience: "1",
        achievements: "Not Provided",
        subjects: "IT/Cs Programming",
        email: "rajeshwari.mistriv@bkbck.edu.in",
    },
    {
        name: "Vinod Rajput",
        designation: "Assistant Professor",
        qualification: "Not Provided",
        experience: "Not Provided",
        achievements: "Not Provided",
        subjects: "CS",
        email: "Not Provided",
    },
    {
        name: "Kajal Jaisinghani",
        designation: "Assistant Professor CS, Coordinator of DS",
        qualification: "MCA, MSc IT, MA(Economics), PhD (Pursuing)",
        experience: "10",
        achievements: "Not Provided",
        subjects: "CS",
        email: "kajal.jaisinghani@bkbck.edu.in",
    },
    {
        name: "Esmita Gupta",
        designation: "Vice Principal",
        qualification: "Not Provided",
        experience: "Not Provided",
        achievements: "Not Provided",
        subjects: "IT",
        email: "Not Provided",
    },
    {
        name: "Pritam Kamble",
        designation: "Assistant Professor",
        qualification: "Not Provided",
        experience: "Not Provided",
        achievements: "Not Provided",
        subjects: "CS",
        email: "Not Provided",
    },
    {
        name: "Vimmi Gajbhije",
        designation: "Assistant Professor",
        qualification: "BE(IT), ME(CSE)",
        experience: "8.5+",
        achievements: "Not Provided",
        subjects: "IT/CS",
        email: "vimmi.gajbhije@bkbck.edu.in",
    },
];

async function seedFaculty() {
    try {
        await dbConnect();
        // Clear existing data
        await Faculty.deleteMany({});

        // Insert new data
        await Faculty.insertMany(facultyData);

        console.log("Faculty data seeded successfully!");
        process.exit(0);
    } catch (error) {
        console.error("Error seeding faculty data:", error);
        process.exit(1);
    }
}

seedFaculty();
